#!/bin/bash

apt update
apt install --yes make git libgtest-dev python3-pip zip gdb gdb-doc pkgconf* linux-tools-common autoconf libtool apt-file libssl-dev
pip3 install --user meson pyelftools ninja gdown pyinstaller

mkdir $HOME/dev
cd $HOME/dev

# modules requires LAG cmake
wget https://github.com/Kitware/CMake/releases/download/v3.28.1/cmake-3.28.1.tar.gz
tar zxf ./cmake-3.28.1.tar.gz
rm -f ./cmake-3.28.1.tar.gz
cd cmake-3.28.1
./bootstrap --prefix=$HOME/local  && make -j32 && make install
cd ..
rm -rf make-3.28.1

# install clang-16 which is not on std 22.04 apt repo lists
# https://askubuntu.com/questions/1473403/how-to-install-clang-16-on-22-04-lts
wget https://apt.llvm.org/llvm.sh
chmod +x llvm.sh
./llvm.sh 16
rm -f ./llvm.sh

# mop up
apt --yes upgrade

#
# Add variables to ~/.bashrc
#
echo "alias ll=\"ls -la\"" >> ${HOME}/.bashrc
echo "alias edit=\"vi\"" >> ${HOME}/.bashrc
echo "alias ppjson=\"python3 -m json.tool\"" >> ${HOME}/.bashrc
echo "export PATH=.:$HOME/local/bin:$HOME/.local/bin:\$PATH" >> ${HOME}/.bashrc

#
# Add variables to .vimrc
#
echo "set expandtab" > ~/.vimrc
echo "set tabstop=2" >> ~/.vimrc
echo "set shiftwidth=2" >> ~/.vimrc
echo "set bg=dark" >> ~/.vimrc
echo "set noautoindent" >> ~/.vimrc
echo "set nosmartindent" >> ~/.vimrc
echo "set nocindent" >> ~/.vimrc
echo "set wrap" >> ~/.vimrc
echo ":syntax off" >> ~/.vimrc
echo ":set colorcolumn=120" >> ~/.vimrc

# git needs this
git config --global user.email "gshanemiller6@gmail.com"
git config --global user.name "smiller"
git config --global credential.helper store
git config --global credential.helper cache
